import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import l1 from "@/public/assets/img/sign-in/1.svg";
import l2 from "@/public/assets/img/sign-in/2.svg";
import Heart from "@/public/assets/img/sign-in/heart.svg";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrimeReactProvider>
          <div className="relative min-h-screen flex bg-white overflow-hidden">
            <div className="w-full md:w-1/2 flex flex-col justify-center items-start px-10 md:px-20 z-10">
              <div className="w-full flex justify-start absolute top-0 left-0 p-5 md:p-10">
                <Image
                  src={Heart}
                  alt="Heart"
                  className="absolute left-7 top-5 w-8 h-8 object-contain"
                />
              </div>
              {children}
            </div>
            <div className="hidden md:flex w-1/2 relative items-center justify-center">
              <Image
                src={l2}
                alt="l2"
                className="absolute right-0 top-0 h-full w-auto object-contain pointer-events-none select-none"
              />
              <Image
                src={l1}
                alt="l1"
                className="absolute right-0 top-0 h-full w-auto object-contain pointer-events-none select-none"
              />
            </div>
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
