import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import Image from "next/image";
import l1 from "@/app/assets/img/sign-in/1.svg";
import l2 from "@/app/assets/img/sign-in/2.svg";
import Heart from "@/app/assets/img/sign-in/heart.svg";
import { cookies } from 'next/headers'
export const metadata: Metadata = {
  title: "Cure",
  description: "Generated by Sarah El3anany",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          <div className="relative min-h-screen flex bg-white overflow-hidden">
            {token ? (
              <div>
                <div className="w-full md:w-1/2 flex flex-col justify-center items-start px-10 md:px-20 z-10">
                  {children}
                </div>
              </div>
             ) : (
              <div>
                <div className="w-full md:w-1/2 flex flex-col justify-center items-start px-10 md:px-20 z-10">
                  <div className="w-full flex justify-start absolute top-0 left-0 p-5 md:p-10">
                    <Image
                      src={Heart}
                      alt="Heart"
                      loading="eager"
                      className="absolute left-7 top-5 w-8 h-8 object-contain"
                    />
                  </div>
                  {children}
                </div>
                <div className="hidden md:flex w-1/2 relative items-center justify-center">
                  <Image
                    src={l2}
                    loading="eager"
                    alt="l2"
                    className="absolute right-0 top-0 h-full w-auto object-contain pointer-events-none select-none"
                  />
                  <Image
                    src={l1}
                    loading="eager"
                    alt="l1"
                    className="absolute right-0 top-0 h-full w-auto object-contain pointer-events-none select-none"
                  />
                </div>
              </div>
             )}
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
