import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import Header from "@/app/components/layouts/header";
import Footer from "@/app/components/layouts/footer";
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import "./globals.css";
import Image from "next/image";
import l1 from "@/app/assets/img/sign-in/1.png";
import l2 from "@/app/assets/img/sign-in/2.png";
import HeartComponent from "./components/SVGs/heart";
import { cookies } from 'next/headers'
export const metadata: Metadata = {
  title: "Cure",
  description: "Generated by Sarah El3anany",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
            {token ? (
             <div className="min-h-screen w-full bg-white overflow-visible">
              <Header />
              <div className="relative w-full flex flex-col items-center justify-center text-center pt-22">
                <div className="absolute inset-0 z-0 w-full h-screen flex items-center justify-center">
                  <div className="absolute md:w-[1200px] md:h-[1200px] w-[400px] h-[400px] border border-neutral-800 rounded-full opacity-10"></div>
                  <div className="absolute md:w-[800px] md:h-[800px] w-[200px] h-[200px] border border-neutral-800 rounded-full opacity-10"></div>
                  <div className="absolute md:w-[300px] md:h-[300px] w-[100px] h-[100px] border border-neutral-800 rounded-full opacity-10"></div>
                </div>
              {children}
              </div>
              <Footer />
            </div>
             ) : (
              <div className="relative min-h-screen flex bg-white">
                <div className="w-full md:w-1/2 flex flex-col justify-center items-start px-10 md:px-20 z-10">
                  <div className="w-full flex justify-start absolute top-0 left-0 p-5 md:p-10">
                    <HeartComponent className="absolute left-7 top-5 w-8 h-8 object-contain" />
                  </div>
                  {children}
                </div>
                <div className="hidden md:flex w-1/2 relative items-center justify-center">
                  <Image
                    src={l2}
                    loading="eager"
                    alt="l2"
                    className="absolute right-0 top-0 h-full w-auto pointer-events-none select-none"
                  />
                  <Image
                    src={l1}
                    loading="eager"
                    alt="l1"
                    className="absolute right-0 top-0 h-full w-auto pointer-events-none select-none"
                  />
                </div>
              </div>
             )}
        </PrimeReactProvider>
      </body>
    </html>
  );
}